### ISSUE TITLE
Example configuration for using vocprez in combination with vocbench

### ISSUE THREAD

**Issue by mielvds** [RDFLib/VocPrez#56]
Hi!

The documentation mentions that vocprez works out of the box with vocbench. Could you provide an example (or docker-compose) on how to set this up? 

Happy to help btw, here's a boilerplate:

```
version: "3"

networks:
  vocnw:
    driver: bridge
  services:
    vocbench3:
      build: ./vocbench3
      image: vocbench
      ports:
      - "1979:1979"
      volumes:
      - "$PWD/data/stdata:/opt/vocbench3/data"
      networks:
        - sparql
    vocnw:
      build: https://github.com/RDFLib/VocPrez.git
      image: vocprez:latest
      restart: unless-stopped
      ports:
      - "5000:5000"
      volumes:
      - $PWD/config/vocprez-config.py:/vocprez/_config/__init__.py
      stdin_open: true
      tty: true
      networks:
        - vocnw
```
How would I need to set up `vocprez-config.py`?
